name: Render Quarto Document

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install R and Dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install Pandoc
        run: |
          sudo apt-get install pandoc

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("quantmod", "rugarch", "MSGARCH", "zoo", "foreach", "dplyr", "tidyr", "ggplot2"))'

      - name: Render Quarto document
        run: |
          quarto render VALA_daily.qmd

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Automated render of VALA_daily.qmd'
          git push
