name: Render and Publish
on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Install R packages
        run: |
          R -e "install.packages('rmarkdown')"
          R -e "install.packages('knitr')"  # In case you need knitr for rendering

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.340

      - name: Render Quarto document
        run: |
          quarto render VALA_daily.qmd

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages  # Rendered HTML files will be pushed here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Secret provided automatically by GitHub Actions
