name: Render documents and upload

on:
  push:
    branches: [main, master]
    tags: ['*']
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight EST
  workflow_dispatch:  # This trigger allows manual workflow runs

jobs:
  render_document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libcurl4-openssl-dev

      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb

      - name: Create Writable R Package Directory
        run: |
          mkdir -p /tmp/rmarkdown
          chmod -R 777 /tmp/rmarkdown

      - name: Install rmarkdown
        run: |
          export R_LIBS_USER="/tmp/rmarkdown"
          R -e "install.packages('rmarkdown', lib='$R_LIBS_USER')"

      - name: Build Quarto Document
        run: |
          quarto render .github/VALA_rmarkdown.Rmd --to pdf

      - name: Cache icons
        uses: actions/cache@v2
        with:
          path: icons
          key: ${{ runner.os }}-${{ hashFiles('get_icons.R') }}

      - name: Get icons
        run: Rscript get_icons.R

      - name: Build slides
        run: Rscript .github/workflows/build_slides.R

      - name: Deploy to Main Repository
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main
