name: Render Quarto Script Daily

on:
  workflow_dispatch:  # This trigger allows manual workflow runs
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC

jobs:
  render-qmd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Quarto
      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb

      # Step 3: Install rmarkdown in a temporary directory
      - name: Install rmarkdown
        run: R -e "install.packages('rmarkdown', lib='/tmp/rmarkdown')"

      # Step 4: Render Quarto Document
      - name: Render Quarto Document
        run: |
          quarto render .github/VALA_script.qmd --to html

      # Step 5: Upload Rendered Output
      - name: Upload Rendered File
        uses: actions/upload-artifact@v3
        with:
          name: rendered-document
          path: VALA_script.html  # Adjust this to the rendered file's name

