name: Render documents and upload

on:
  push:
    branches: [main, master]
    tags: ['*']
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight EST
  workflow_dispatch:  # This trigger allows manual workflow runs

jobs:
  render_document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libcurl4-openssl-dev

      - name: Install R packages
        run: |
          export R_LIBS_USER="/usr/local/lib/R/site-library"
          R -e "install.packages(c('rmarkdown', 'knitr', 'dplyr', 'tidyverse', 'palmerpenguins', 'quantmod', 'rugarch', 'MSGARCH', 'zoo', 'foreach', 'formattable', 'ggpubr', 'ggplot2'), lib='$R_LIBS_USER')"

      - name: Render .Rmd file
        run: |
          Rscript -e "rmarkdown::render('.github/VALA_rmarkdown.Rmd')"

      - name: Deploy to Main Repository
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main
